# default settings used throughout this flake

[user]
name = "midchildan"
fullName = "midchildan"
homeDirectory = "/home/midchildan"
email = "git@midchildan.org"
gpgKey = "FEF0AE2D544934825F0640AA186A1EDAC5C63F83"

# NOTE: Make sure to understand what the following does. It's a good idea to
# override this option this per host.
#
# https://nix-community.github.io/home-manager/options.html#opt-home.stateVersion
stateVersion = "23.05"

[user.darwin]
homeDirectory = "/Users/midchildan"

[os]
system = "x86_64-linux"

# NOTE: Make sure to understand what the following does. It's a good idea to
# override this option this per host.
#
# https://search.nixos.org/options?show=system.stateVersion&query=system.stateVersion
# https://nixos.wiki/wiki/FAQ/When_do_I_update_stateVersion
stateVersion = "23.05"

[os.darwin]
system = "x86_64-darwin"

# NOTE: Make sure to understand what the following does. It's a good idea to
# override this option this per host.
#
# https://daiderd.com/nix-darwin/manual/index.html#opt-system.stateVersion
stateVersion = 4

[nix]
package = "nix_2_13"
